### ISSUE TITLE
keep order of columns?

### ISSUE THREAD

**Issue by biocyberman** [slzhao/heatmap3#1]
Hi,
I am trying out heatmap3. I have columns as different time points and rows as gene expressions at each time points. The heatmap produced by heatmap3 reorder the time points (columns). How do I force it to keep the column order?

Thanks

**Comment by slzhao** [comment]
Hello,

Try adding "Colv=NA" in your code. Thanks!

2015-12-16 6:56 GMT-06:00 biocyberman notifications@github.com:

**Comment by biocyberman** [comment]
That works, fantastic! Thanks
