### ISSUE TITLE
scale = "row" or "none" does not affect clustering.

### ISSUE THREAD

**Issue by wolski** [slzhao/heatmap3#10]
I would expect that row scaling would affect column clustering
but it doesn't.

```
 x <- matrix(rnorm(100),ncol=5)
heatmap3::heatmap3(x)
heatmap3::heatmap3(x, scale="none")
heatmap3::heatmap3(x, scale="row")
heatmap3::heatmap3(t(scale(t(x))), scale="none")
```

**Comment by slzhao** [comment]
Hello wolski,
This is derived from the original heatmap function in R. Scale of x is after clustering and only influence the color of heatmap, not clustering.
