### ISSUE TITLE
How to put title or and ggplot like operations?

### ISSUE THREAD

**Issue by biocyberman** [slzhao/heatmap3#3]
How do I put title in heatmaps?
And how do I put the heatmap in a panel with `gridExtra` package or `cowplot` package?

I tried do something like `myplotobject <- heatmap3(...)` and use `myplotobject` in other plot manipulation steps but `myplotobject` is not really a plot object. So I failed.

**Comment by slzhao** [comment]
Hello biocyberman,

To make heatmap3 completely compatible with the heatmap function in R, it
was developed by R basic graphic functions which were used in heatmap. It
is not a ggplot2 style package and can't be used in packages like gridExtra.
If you want to combine more than one heatmap into one figure in R, you can
try other ggplot2 style heatmap packages, for example, this one:
https://bioconductor.org/packages/release/bioc/vignettes/ComplexHeatmap/inst/doc/s3.a_list_of_heatmaps.html

2016-03-17 9:19 GMT-05:00 biocyberman notifications@github.com:
