### ISSUE TITLE
No RowSideColors

### ISSUE THREAD

**Issue by kmholton** [slzhao/heatmap3#4]
Hi,
I have a similar problem with  heatmap.2 and your heatmap3, in that the RowSideColors are not displayed.  I was hoping your package corrected the issue.  Without modifying myRowSideColors, it displays:
Error in agglo.FUN(vals[iOrd]) : invalid 'type' (character) of argument 
I tried turning myRowSideColors into a character, but it displays Error in agglo.FUN(vals[iOrd]) : invalid 'type' (character) of argument
I turn it into a factor, and I get no error, but also no RowSideColors. 

For context, in  heatmap.2, I also get no RowSideColors, and when  I turn on  row dendrograms along with passing the  RowSideColors argument, the plot completely misrenders, making the row dendrograms vertical, and the main off to the side.

This holds true in R 3.2.1 and R 3.1.2, on a Windows 8 machine and on a CentOS 6 (R 3.2.1 and 3.1.2) box.

I have included link to the github repo with a small toy script and de-identified data. Any help or suggestions would be most appreciated.  Thanks!

https://github.com/kmholton/testcases

**Comment by slzhao** [comment]
Hi kmholton,

tested your data and code. It works after some changes.
Please change this in your heatmap3 function and it should be ok:

RowSideColors=as.character(FmyRowSideColors)

2016-04-20 15:27 GMT-05:00 kmholton notifications@github.com:

**Comment by kmholton** [comment]
That works!  Thank you so much for your speedy support!  Feel free to close the issue.
Best,
kmholton
