### ISSUE TITLE
Code blocks out of page in vignette PDF file

### ISSUE THREAD

**Issue by JackieMium** [slzhao/heatmap3#5]
Really enjoy using this package to draw beautiful heatmaps without having to tuning so many plot details. But I found that  code blocks out of page margin occured quite a lot in the package vignette PDF file.  Wonder if the author is aware of that and intend to do some ajustments to avoid that.
![image](https://user-images.githubusercontent.com/12944832/32479912-0ce2379c-c3c7-11e7-98b9-655e8e0e7a63.png)

**Comment by slzhao** [comment]
I do see that. Do you know what is the best way to avoid it? Thanks~

Shilin

**Comment by JackieMium** [comment]
I think the simplest way to avoid this is to wrap the long lines of code into multiple line:

```R
highlightCell <- dataframe(row = c(2, 4, 6), col = c(1, 3, 5), 
                           color = c('red', 'green' ,'blue'))
```
This also helps to read the code by the way.

**Comment by slzhao** [comment]
Oh. I thought there were some settings to change it.
Will add it to my to do list and change in next version.

Thanks!
Shilin

**Comment by slzhao** [comment]
version 1.1.8 fixed this. Thanks!
