### ISSUE TITLE
Remove legend

### ISSUE THREAD

**Issue by akastrin** [slzhao/heatmap3#6]
There is no instructions how to remove legend (key) in the documentation. Could you please provide an example.

**Comment by slzhao** [comment]
Hello,

The heatmap function in R has no legend. If you want to use heatmap3, try
below:
heatmap3(matrix(rnorm(10),ncol=2),legendfun=function()
plot(0,0,bty="n",xaxt="n",yaxt="n",type="n"))

**Comment by terrimporter** [comment]
Just wanted to add an easier way to remove the legend in case anyone needs this:
heatmap3(mat, legendfun=function() plot.new())
